service: Employee-Banks-Detail-All-api
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employeeTable}
custom:
  employeeTable: banksDetailInfo-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  bankDetailsAll:
    handler: api.bankDetailsAll
    name: create-apis
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: employee/bankDetails
          method: POST
      - http:
          path: employee/bankDetails/{empId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
        Resource: !GetAtt EmployeeTable.Arn
    # events:
    #   - http:
    #       method: POST
    #       path: createBankDetialsInfo
    #       cors: true
    #   - http:
    #       method: PUT
    #       path: updateBankDetialsInfo/{empId}
    #       cors: true
    #   - http:
    #       method: GET
    #       path: getEmployeeBankDetialsInfo/{empId}
    #       cors: true
    #   - http:
    #       method: GET
    #       path: getAllEmployeesBankDetialsInfo
    #       cors: true
    #   - http:
    #       method: DELETE
    #       path: deleteBankDetialsInfo/{empId}
    #       cors: true
    #   - http:
    #       method: DELETE
    #       path: softDeleteBankDetialsInfo/{empId}
    #       cors: true
    # iamRoleStatements:
    #   - Effect: "Allow"
    #     Action:
    #       - "dynamodb:PutItem"
    #       - "dynamodb:UpdateItem"
    #       - "dynamodb:DeleteItem"
    #       - "dynamodb:Scan"
    #       - "dynamodb:GetItem"
    #     Resource: !GetAtt EmployeeTable.Arn
    # iamRoleStatementsName: Employee-Banks-Detail-All-api-dev-lambda
resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTable}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES